from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('recipe/<int:recipe_id>/', views.recipe_detail, name='recipe_detail'),
    path('recipe/<int:recipe_id>/rate/', views.rate_recipe, name='rate_recipe'),
    path('recipe/random/', views.random_recipe, name='random_recipe'),
    path('privacy/', views.privacy, name='privacy'),
    path('search/', views.search, name='search'),
    path('terms/', views.terms, name='terms'),
    path('send-feedback/', views.send_feedback, name='send-feedback'),
    path('suggest/', views.suggest_recipe, name='suggest_recipe'),
    path('recipe/<int:recipe_id>/comment/', views.add_comment, name='add_comment'),
    path('comment/<int:comment_id>/like/', views.toggle_comment_like, name='toggle_comment_like'),
    path('favorites/', views.favorites, name='favorites'),
    path('settings/', views.settings_page, name='settings'),
    path('api/settings/', views.api_settings, name='api_settings'),
    path('api/favorites/add/', views.api_favorite_add, name='api_favorite_add'),
    path('api/favorites/remove/', views.api_favorite_remove, name='api_favorite_remove'),
    path('ai/ask/', views.ai_ask, name='ai_ask'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/<str:username>/', views.profile_view, name='profile'),
    path('edit-profile/', views.edit_profile_view, name='edit_profile'),
    path('api/push/subscribe/', views.api_push_subscribe, name='api_push_subscribe'),
    path('api/push/unsubscribe/', views.api_push_unsubscribe, name='api_push_unsubscribe'),
    path('api/notifications/', views.api_notification_settings, name='api_notification_settings'),
    path('api/vapid-key/', views.vapid_public_key, name='api_vapid_key'),
    path('recipe/<int:recipe_id>/pdf/', views.download_recipe_pdf, name='download_recipe_pdf'),
]